package com.jay.wechat.dao;

import com.github.pagehelper.Page;
import com.jay.wechat.po.SubServ;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

public interface SubServMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_serv
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_serv
     *
     * @mbggenerated
     */
    int insert(SubServ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_serv
     *
     * @mbggenerated
     */
    SubServ selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_serv
     *
     * @mbggenerated
     */
    List<SubServ> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_serv
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SubServ record);

    Page<SubServ> findByPage();
}